### ISSUE TITLE
Support multi-line envs/commands

### ISSUE THREAD

**Issue by michaelcontento** [michaelcontento/circleci-matrix#10]

**Comment by winksaville** [comment]
Funny, I was just going to file an issue on this. Did you see my post on the discussion list related to using [yaml block literals](https://discuss.circleci.com/t/conditional-expressions-work-if-used-with-yamal-block-literals/670/15)?

I was thinking the easiest way might be to implement circleci-matrix in python, what are you thinking?

**Comment by michaelcontento** [comment]
Yes, I stumbled over the discussion and filed this issue :smile: 

I'm not sure about python. I'd love to keep this as simple and easy to install as possible. And Yaml is, AFAIK, not readable by python without some kind of dependency. Maybe there is a good (enough) yaml parser for bash out there?

**Comment by winksaville** [comment]
Using block literals really makes the circle.yml much more usable to my
mind. Yes using python will would definitely create a dependency on python
and the pyyaml library, but personally I'd take that hit, of course its
your baby. I did a quick search and didn't see any bash scripts which
looked suitable but maybe there is or maybe you can just knock one out in
bash.

**Comment by michaelcontento** [comment]
I think I'll attack this issue sometime this week. But if it's to hard/ugly/buggy, python might be a good alternative. 

Do you have some good examples for block literals? Are there other ways of multi-line strings in yaml? It would be awesome if you could provide me with some examples / edge-cases we should support. It's fine to just paste them here in this conversation.

**Comment by winksaville** [comment]
You can see some trivial examples in that conversation. I haven't used it
for real and won't be until its in your code :)

I'll gladly review and help anyway I can, just let me know.

**Comment by michaelcontento** [comment]
Hi @winksaville,

please have a look at the new PR #12 and my - more or less pretty - solution. I'll add some more tests tomorrow and rethink / revisit the implementation with a fresh mind before merging. But it should be ready for you to play around :)

Oh, and if you find any bugs / problems, please report them in the PR!

Thanks

**Comment by winksaville** [comment]
I'll take a look tomorrow.

**Comment by winksaville** [comment]
I've added a pull request:
https://github.com/michaelcontento/circleci-matrix/pull/13 with three tests
I think should work. The pertinent section of the [yaml spec](http://yaml.org/spec/1.2/spec.html) is [8.1 Block Scalar Styles](http://yaml.org/spec/1.2/spec.html#id2793652). And of course using the
[online parser](https://yaml-online-parser.appspot.com/) really helps.

If you want "talk" via Hangouts, I'm "wink@saville.com", I'll be up about
0700 Pacific Standard Time.

Cheers,

Wink
