### ISSUE TITLE
circle.yml doesn't support linux

### ISSUE THREAD

**Issue by winksaville** [michaelcontento/circleci-matrix#11]
circle.yml only supports xcode and those of us without access to the circleci xcode system have to modify it, this is inconvenient at a minimum. I posted ["how to use circleci for linux, xcode, .. in one project"](https://discuss.circleci.com/t/how-to-use-circleci-for-linux-xcode-in-one-project/693) to hopefully see if there is a solution.

**Comment by michaelcontento** [comment]
Yes, I've talked with the CircleCI guys about this too and it seems, at least to me, that support for multi-OS builds will not appear anytime soon :(

But I've enabled **Permissive building of fork pull requests** and now every PR should run with my account on CircleCI (with the enabled OSX support). 

The linux hosts are monitored on [TravisCI](https://travis-ci.org/michaelcontento/circleci-matrix) via our [.travis.yml](https://github.com/michaelcontento/circleci-matrix/blob/master/.travis.yml). 

Closed, as there is nothing we can do about this. For contributions it's fine to run the test locally and let both CircleCI and TravisCI run for each PR.
