### ISSUE TITLE
Supports Circle CI 2.0?

### ISSUE THREAD

**Issue by sdolenc** [michaelcontento/circleci-matrix#24]
Does this work for Circle CI 2.0? Sorry if this is answered elsewhere

**Comment by michaelcontento** [comment]
I'm not sure about the difference between Circle CI 2.0 and pre 2.0 to be honest 😅 

But it's a basic bash script without any special dependencies, so from this point there should nothing be against using this on Circle CI 2.0

Feel free to open a new issue if you detect something broken 👍

**Comment by sdolenc** [comment]
in case others encounter this issue: I figured out how to do a circleci-matrix using their 2.0 syntax and yaml anchors

the yaml file I wrote can be found here:
https://github.com/sdolenc/oxa-tools/blob/odf_ci3/.circleci/config.yml
